{{--
-- This is a blade file which can pull from many templates to create a single
-- php file that is then used to display the webpage.
-- The curly braces will be replaced with php code autogenerated by the framework
--}}

{{--
-- Here were using the Form library to create an html form that will work with
-- the library. The form starts at the open tag and ends at the close tag
-- The form will submit to the route named echo.output 
--}}
{!! Form::open(['route' => 'echo.output']) !!}
<div>
{!! Form::label('name', 'Your Name:') !!}
{!! Form::text('name', null, null) !!}
</div>
<div>
{!! Form::submit('Submit', null) !!}
</div>

{!! Form::close() !!}


{{--
-- 
--}}
@isset($bname)
<div>
    Hello, {{ $bname }}
</div>
@endisset

@if($errors->any())
<div>
Errors:
<ul>
@foreach ($errors->all() as $error)
    <li>{{ $error }}</li>
@endforeach
</ul>
</div>
@endif
